backend:
  name: github
  repo: Don-Helios/donhelios-web
  branch: main
  base_url: https://auth.donhelios.com
  auth_endpoint: auth
  site_domain: donhelios.com

# Media settings
media_folder: "site/assets/images/uploads"
public_folder: "/assets/images/uploads"

# Site URL (important for HTTPS context)
site_url: https://donhelios.com

# Collections
collections:
  # Blog Posts
  - name: "posts"
    label: "Blog Posts"
    folder: "site/collections/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Author"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Content", name: "body", widget: "markdown"}

  # Projects
  - name: "projects"
    label: "Projects"
    folder: "site/collections/_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Project URL", name: "url", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown"}

  # Testimonials
  - name: "testimonials"
    label: "Testimonials"
    folder: "site/collections/_testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "testimonial"}
      - {label: "Client Name", name: "name", widget: "string"}
      - {label: "Client Position", name: "position", widget: "string"}
      - {label: "Client Company", name: "company", widget: "string", required: false}
      - {label: "Client Photo", name: "image", widget: "image", required: false}
      - {label: "Rating", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, required: false}
      - {label: "Testimonial Content", name: "body", widget: "markdown"}

  # Pages
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "site/collections/_pages/about.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}
      
      - label: "Blog Page"
        name: "blog"
        file: "site/collections/_pages/blog.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}
      
      - label: "Projects Page"
        name: "projects_page"
        file: "site/collections/_pages/projects.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}
      
      - label: "Elements Page"
        name: "elements"
        file: "site/collections/_pages/elements.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}

  # Site Settings & Data Files
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general_settings"
        file: "site/_data/general_settings.yml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Social Media Share Image", name: "social_media_share_image", widget: "image"}
          - {label: "Disqus Identifier", name: "disqus-identifier", widget: "string", required: false}
          - {label: "Google Analytics ID", name: "google-analytics", widget: "string", required: false}
      
      - label: "Navigation"
        name: "navigation"
        file: "site/_data/navigation.yml"
        fields:
          - {label: "Logo Image", name: "logo_image", widget: "image"}
          - label: "Menu Settings"
            name: "menu__settings"
            widget: "object"
            fields:
              - label: "Menu Items"
                name: "menu__items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
                  - label: "Submenu"
                    name: "submenu"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "URL", name: "url", widget: "string"}
      
      - label: "Footer"
        name: "footer"
        file: "site/_data/footer.yml"
        fields:
          - label: "Footer Menu Settings"
            name: "footer_menu__settings"
            widget: "object"
            fields:
              - label: "Menu Items"
                name: "menu__items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
          - {label: "Copyright Text (HTML)", name: "copyright_text_html", widget: "text"}
      
      - label: "Author Info"
        name: "author"
        file: "site/_data/author.yml"
        fields:
          - {label: "Author Name", name: "author_name", widget: "string"}
          - {label: "Author Image", name: "author_image", widget: "image"}
      
      - label: "Newsletter"
        name: "newsletter"
        file: "site/_data/newsletter.yml"
        fields:
          - {label: "Newsletter Title", name: "newsletter_title", widget: "string"}
          - {label: "Newsletter Description", name: "newsletter_description", widget: "text"}
          - {label: "Newsletter Identifier (MailChimp)", name: "newsletter_identifier", widget: "string"}
          - {label: "Newsletter Button Text", name: "newsletter_button", widget: "string"}
      
      - label: "Social Links"
        name: "social_links"
        file: "site/_data/social_links.yml"
        fields:
          - label: "Social Media Links"
            name: "social"
            widget: "list"
            fields:
              - {label: "Icon Name", name: "icon", widget: "string"}
              - {label: "Link URL", name: "link", widget: "string"}
