backend:
  name: github
  repo: Don-Helios/donhelios-web
  branch: main
  base_url: https://auth.donhelios.com
  auth_endpoint: auth
  site_domain: donhelios.com

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: https://donhelios.com

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", default: "Don Helios"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "blog.md"
        label: "Blog Page"
        name: "blog"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "projects.md"
        label: "Projects Page"
        name: "projects"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "projects"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
